### ISSUE TITLE
improve documentation for user with swap activate

### ISSUE THREAD

**Issue by frenchdeepweb** [nya-furball/gpgs#1]
If user use swap on his system he get only
`Warning: there are active swapfiles/partitions!
Key can be swapped into non-volatile storage! Exiting.`

regular users don't know how to deactivate swap, maybe it can be a good idea to add this

```
You can deactivate swap on this system with command:
`swapoff -a`
Warning: You must be root or use sudo for launch this command

```

**Comment by nya-furball** [comment]
Done. See commit 0feb2ce09fd1e9209f5362f608e5fa694e381513.
